apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: notifications-service
  namespace: {{ .Release.Namespace }}
spec:
  configurationSpec:
    template:
      spec:
        containers:
          - name: notifications-service
            image: {{ .Values.images.notificationsService }}

  scaleSpec:
    metric: concurrency
    minReplicas: {{ .Values.scale.minReplicas }}
    maxReplicas: {{ .Values.scale.maxReplicas }}
    scaleDelaySeconds: {{ .Values.scale.scaleDelaySeconds }}

  logSpec:
    type: elastic-datastream
    host: {{ .Values.elastic.host | quote }}
    user: {{ .Values.elastic.user | quote }}
    passwordSecret: {{ .Values.elastic.secret.name }}
    passwordKey: {{ .Values.elastic.passwordKey }}

  eventSourcesSpec:
    sources:
      - name: status-consumer
        kafkaSourceConfiguration:
          bootstrapServers:
            {{- range .Values.kafka.brokers }}
            - {{ . | quote }}
            {{- end }}
          topics:
            - {{ .Values.kafka.statusTopic }}
          secretRef:
            name: {{ .Values.kafka.secret.name }}
