{{- if .Values.kafka.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kafka.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  user: {{ .Values.kafka.secret.user | quote }}
  password: {{ .Values.kafka.secret.password | quote }}
  sasl.mechanism: {{ .Values.kafka.secret.saslMechanism | quote }}
{{- end }}
---
{{- if .Values.elastic.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elastic.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.elastic.passwordKey }}: {{ .Values.elastic.secret.password | quote }}
{{- end }}
